//! `rf-musette-lab touch`: measures Key Touch's edges for every treble key
//! (milestone 9h again) -- the shallowest curtain at which it holds a steady
//! tone, each rank alone, at each of the pressures -- and writes
//! `crates/rf-musette-dsp/src/touch.rs`.

use rf_musette_analysis::key_edge;
use rf_musette_dsp::compass::{FIRST_KEY, KEYS};
use rf_musette_dsp::touch::{PRESSURES, RANK_KINDS};
use std::{error::Error, fs};

/// The registers that open one rank of each kind: Bassoon (L), Clarinet
/// (M, standing for M− and M+ too), Piccolo (H). One rank alone: Musette's
/// three 8′ beat, its level wobbling a dB from half second to half second,
/// and the steady test reads the wobble as a dying note (the A3's edge came
/// out 0.53 at 200 Pa in Musette, though it sounds at 0.22).
const ONE_RANK: [f64; RANK_KINDS] = [0.0, 11.0, 13.0];

pub fn write() -> Result<(), Box<dyn Error>> {
    // The keys in parallel, each thread with a stack an engine fits on.
    let threads = std::thread::available_parallelism().map_or(4, |n| n.get());
    let keys: Vec<usize> = (0..KEYS).collect();
    // For each key: by pressure and kind, the edge -- 1, the key fully down,
    // where the rank does not sound.
    let results: Vec<(usize, Vec<[f64; RANK_KINDS]>)> = std::thread::scope(|scope| {
        let handles: Vec<_> = keys
            .chunks(KEYS.div_ceil(threads))
            .map(|chunk| {
                let chunk = chunk.to_vec();
                std::thread::Builder::new()
                    .stack_size(64 << 20)
                    .spawn_scoped(scope, move || {
                        chunk
                            .into_iter()
                            .map(|index| {
                                let key = FIRST_KEY + index as u8;
                                let rows = PRESSURES
                                    .iter()
                                    .map(|pressure| {
                                        ONE_RANK.map(|register| {
                                            key_edge(key, register, *pressure).unwrap_or(1.0)
                                        })
                                    })
                                    .collect();
                                eprintln!("key {key} measured");
                                (index, rows)
                            })
                            .collect::<Vec<_>>()
                    })
                    .expect("a measuring thread")
            })
            .collect();
        handles
            .into_iter()
            .flat_map(|handle| handle.join().expect("a measurement"))
            .collect()
    });
    let mut table = vec![[[1.0f64; KEYS]; RANK_KINDS]; PRESSURES.len()];
    for (index, rows) in results {
        for (pressure, kinds) in rows.into_iter().enumerate() {
            for (kind, edge) in kinds.into_iter().enumerate() {
                table[pressure][kind][index] = edge;
            }
        }
    }
    let mut text = String::new();
    text.push_str("//! Generated by `rf-musette-lab touch`; do not edit.\n//!\n");
    text.push_str("//! Key Touch's edges for each treble key (milestone 9h again): the\n");
    text.push_str("//! shallowest pallet curtain, as a share of the M rank's hole, at which\n");
    text.push_str("//! the key holds a steady tone with one rank of each kind alone (L; M,\n");
    text.push_str("//! standing for M− and M+; H), the arm's bellows asked for each of\n");
    text.push_str("//! [`PRESSURES`]; 1 where the rank does not sound fully down.\n\n");
    text.push_str("/// The pressures the edges are measured at, Pa.\n");
    text.push_str(&format!(
        "pub const PRESSURES: [f64; {}] = {:?};\n\n",
        PRESSURES.len(),
        PRESSURES
    ));
    text.push_str("/// The kinds of rank measured: L, M, H.\n");
    text.push_str(&format!("pub const RANK_KINDS: usize = {RANK_KINDS};\n\n"));
    text.push_str("/// By pressure, kind and key (F3-A6).\n");
    text.push_str(&format!(
        "pub const EDGE: [[[f32; {KEYS}]; {RANK_KINDS}]; {}] = [\n",
        PRESSURES.len()
    ));
    for kinds in &table {
        text.push_str("    [\n");
        for row in kinds {
            text.push_str("        [\n");
            for value in row {
                text.push_str(&format!("            {value:.3},\n"));
            }
            text.push_str("        ],\n");
        }
        text.push_str("    ],\n");
    }
    text.push_str("];\n");
    let path = super::package::workspace_root()?.join("crates/rf-musette-dsp/src/touch.rs");
    fs::write(&path, text)?;
    println!("Wrote {}", path.display());
    Ok(())
}
