//! `rf-musette-lab tune`: finishes every reed of the treble, the bass side
//! and the free bass (8p) as a maker would -- loads the low ones until they
//! speak across the bellows' range, then tunes each -- and writes the tables
//! the engine reads, `crates/rf-musette-dsp/src/tuning.rs`.

use rf_musette_analysis::{Finish, voice, voice_free};
use rf_musette_dsp::Parameters;
use std::{error::Error, fs};

const RANK_NAMES: &str = "L, M−, M, M+, H";
const BASS_RANK_NAMES: &str = "16′, 8′, 8-4′, 4′, 2′";

/// One table's source text: `rows` of finishes, the field `pick` picks.
fn table<const N: usize>(
    name: &str,
    rows: &[[Option<Finish>; N]],
    pick: impl Fn(Finish) -> f64,
    what: &str,
) -> Result<String, Box<dyn Error>> {
    let mut text = format!("pub const {name}: [[f32; {N}]; {}] = [\n", rows.len());
    for (rank, row) in rows.iter().enumerate() {
        text.push_str("    [\n");
        for (index, cell) in row.iter().enumerate() {
            let cell =
                cell.ok_or_else(|| format!("{what} rank {rank}, reed {index} does not speak"))?;
            text.push_str(&format!("        {:.3},\n", pick(cell)));
        }
        text.push_str("    ],\n");
    }
    text.push_str("];\n");
    Ok(text)
}

/// The tables' source text for the default parameters.
pub fn source() -> Result<String, Box<dyn Error>> {
    let (treble, bass) = voice(&Parameters::default());
    let mut text = String::from(
        "//! Generated by `rf-musette-lab tune`; do not edit. Tests check it\n\
         //! against a fresh finishing.\n\
         //!\n\
         //! For each reed, as a maker finishes it with the default parameters:\n\
         //! the least tip load, over its unloaded tongue's modal mass, that lets a\n\
         //! low reed speak at 50 Pa, 300 Pa and the bellows' ceiling; the least\n\
         //! inlet duct, a multiple of its tone hole's depth, with which a low reed\n\
         //! speaks on the bellows; then the cents by which its mode sits above\n\
         //! the pitch it must sound at 300 Pa -- or, for a reed that does not\n\
         //! speak there, at the lowest pressure it does: what a tuner files in.\n\n",
    );
    text.push_str(&format!(
        "/// The treble's, for each rank ({RANK_NAMES}) and key (F3-A6).\n"
    ));
    text.push_str(&table("CENTS", &treble, |cell| cell.cents, "treble")?);
    text.push_str(&format!(
        "\n/// The bass side's, for each rank ({BASS_RANK_NAMES}) and pitch class\n/// (C-B).\n"
    ));
    text.push_str(&table("BASS_CENTS", &bass, |cell| cell.cents, "bass")?);
    text.push_str("\n/// The treble's tip loads, by rank and key as `CENTS`.\n");
    text.push_str(&table("LOADS", &treble, |cell| cell.load, "treble")?);
    text.push_str("\n/// The bass side's tip loads, by rank and pitch class as `BASS_CENTS`.\n");
    text.push_str(&table("BASS_LOADS", &bass, |cell| cell.load, "bass")?);
    text.push_str("\n/// The treble's inlet ducts, as multiples of the tone hole's depth.\n");
    text.push_str(&table("DUCTS", &treble, |cell| cell.duct, "treble")?);
    text.push_str("\n/// The bass side's inlet ducts, as multiples of the tone hole's depth.\n");
    text.push_str(&table("BASS_DUCTS", &bass, |cell| cell.duct, "bass")?);
    // The free bass (milestone 8p).
    let free = voice_free(&Parameters::default());
    text.push_str("\n/// The free bass's, for each voice (8′, 4′) and note (E1-C♯6).\n");
    text.push_str(&table("FREE_CENTS", &free, |cell| cell.cents, "free bass")?);
    text.push_str("\n/// The free bass's tip loads, by voice and note as `FREE_CENTS`.\n");
    text.push_str(&table("FREE_LOADS", &free, |cell| cell.load, "free bass")?);
    text.push_str("\n/// The free bass's inlet ducts, as multiples of the tone hole's depth.\n");
    text.push_str(&table("FREE_DUCTS", &free, |cell| cell.duct, "free bass")?);
    Ok(text)
}

pub fn write() -> Result<(), Box<dyn Error>> {
    let path = super::package::workspace_root()?.join("crates/rf-musette-dsp/src/tuning.rs");
    fs::write(&path, source()?)?;
    println!("Wrote {}", path.display());
    Ok(())
}
