//! `rf-musette-lab tune`: tunes the treble as a tuner would and writes the
//! table the engine reads, `crates/rf-musette-dsp/src/tuning.rs`.

use rf_musette_analysis::tune;
use rf_musette_dsp::Parameters;
use std::{error::Error, fs};

/// The table's source text for the default parameters.
pub fn source() -> Result<String, Box<dyn Error>> {
    let table = tune(&Parameters::default());
    let mut text = String::from(
        "//! Generated by `rf-musette-lab tune`; do not edit. A test checks it\n\
         //! against a fresh tuning.\n\
         //!\n\
         //! For each rank (L, M−, M, M+, H) and key (F3-A6), the cents by which a\n\
         //! reed's mode sits above the pitch it must sound at 300 Pa -- or, for a\n\
         //! reed that does not speak there, at the lowest pressure it does -- with\n\
         //! the default parameters: what a tuner files in.\n\n\
         pub const CENTS: [[f32; 41]; 5] = [\n",
    );
    for (rank, row) in table.iter().enumerate() {
        text.push_str("    [\n");
        for (key, cell) in row.iter().enumerate() {
            let cents = cell
                .ok_or_else(|| format!("rank {rank}, key {} does not speak at 300 Pa", 53 + key))?;
            text.push_str(&format!("        {cents:.2},\n"));
        }
        text.push_str("    ],\n");
    }
    text.push_str("];\n");
    Ok(text)
}

pub fn write() -> Result<(), Box<dyn Error>> {
    let path = super::package::workspace_root()?.join("crates/rf-musette-dsp/src/tuning.rs");
    fs::write(&path, source()?)?;
    println!("Wrote {}", path.display());
    Ok(())
}
