//! `rf-musette-lab tune`: finishes every reed of the treble and the bass
//! side as a maker would -- loads the low ones until they speak across the
//! bellows' range, then tunes each -- and writes the tables the engine
//! reads, `crates/rf-musette-dsp/src/tuning.rs`.

use rf_musette_analysis::voice;
use rf_musette_dsp::Parameters;
use std::{error::Error, fs};

const RANK_NAMES: &str = "L, M−, M, M+, H";
const BASS_RANK_NAMES: &str = "16′, 8′, 8-4′, 4′, 2′";

/// One table's source text: `rows` of `(load, cents)`, the field `pick`
/// picks.
fn table<const N: usize>(
    name: &str,
    rows: &[[Option<(f64, f64)>; N]],
    pick: impl Fn((f64, f64)) -> f64,
    what: &str,
) -> Result<String, Box<dyn Error>> {
    let mut text = format!("pub const {name}: [[f32; {N}]; {}] = [\n", rows.len());
    for (rank, row) in rows.iter().enumerate() {
        text.push_str("    [\n");
        for (index, cell) in row.iter().enumerate() {
            let cell =
                cell.ok_or_else(|| format!("{what} rank {rank}, reed {index} does not speak"))?;
            text.push_str(&format!("        {:.3},\n", pick(cell)));
        }
        text.push_str("    ],\n");
    }
    text.push_str("];\n");
    Ok(text)
}

/// The tables' source text for the default parameters.
pub fn source() -> Result<String, Box<dyn Error>> {
    let (treble, bass) = voice(&Parameters::default());
    let mut text = String::from(
        "//! Generated by `rf-musette-lab tune`; do not edit. Tests check it\n\
         //! against a fresh finishing.\n\
         //!\n\
         //! For each reed, as a maker finishes it with the default parameters:\n\
         //! the least tip load, over its unloaded tongue's modal mass, that lets a\n\
         //! low reed hold a tone at 50 Pa, 300 Pa and the bellows' ceiling; then\n\
         //! the cents by which its mode sits above the pitch it must sound at\n\
         //! 300 Pa -- or, for a reed that does not speak there, at the lowest\n\
         //! pressure it does: what a tuner files in.\n\n",
    );
    text.push_str(&format!(
        "/// The treble's, for each rank ({RANK_NAMES}) and key (F3-A6).\n"
    ));
    text.push_str(&table("CENTS", &treble, |cell| cell.1, "treble")?);
    text.push_str(&format!(
        "\n/// The bass side's, for each rank ({BASS_RANK_NAMES}) and pitch class\n/// (C-B).\n"
    ));
    text.push_str(&table("BASS_CENTS", &bass, |cell| cell.1, "bass")?);
    text.push_str("\n/// The treble's tip loads, by rank and key as `CENTS`.\n");
    text.push_str(&table("LOADS", &treble, |cell| cell.0, "treble")?);
    text.push_str("\n/// The bass side's tip loads, by rank and pitch class as `BASS_CENTS`.\n");
    text.push_str(&table("BASS_LOADS", &bass, |cell| cell.0, "bass")?);
    Ok(text)
}

pub fn write() -> Result<(), Box<dyn Error>> {
    let path = super::package::workspace_root()?.join("crates/rf-musette-dsp/src/tuning.rs");
    fs::write(&path, source()?)?;
    println!("Wrote {}", path.display());
    Ok(())
}
